let cardNames = [
    "Public",
    "Private",
    "Rural",
    "Suburban",
    "Urban",
    "Liberal",
    "Conservative",
    "Religious",
    "Diverse",
    "Beach",
    "Mountains",
    "Under 4 Hour Drive(home for the weekend)",
    "4 - 7 Hour Drive(home for long weekend)",
    "Far From Home (have to fly)",
    "High In-State Population",
    "High International Population",
    "High First-Gen Population",
    "Hispanic Serving Institution",
    "HBCU",
    "Out-of-Country",
    "Northeast",
    "Southwest",
    "Southeast",
    "Midwest",
    "West Coast",
    "Under 1,000 Students",
    "1,000 - 3,999 Students",
    "4,000 - 9,999 Students",
    "10,000 - 14,999 Students",
    "15,000 - 24,999 Students",
    "Over 25,000 Students",
    "Direct Entry to Major",
    "Free Academic Resources (tutoring, writing center, math lab, etc)",
    "Classes taught by Professors",
    "Small class size (under 30)",
    "Academic accommodations",
    "Lecture courses",
    "Bachelors/Masters Programs",
    "Liberal Arts",
    "STEM",
    "Learning Communities",
    "Test Optional",
    "Honors Program",
    "Experiential Learning",
    "Resources for Undecided Students",
    "Undergrad Research",
    "Accelerated Med Program",
    "Accelerated Law Program",
    "Accelerated MBA Program",
    "Service Learning Requirement",
    "Discussion Courses",
    "Ability to have a Minor",
    "Ability to Double Major",
    "Service Clubs",
    "Marching Band",
    "Musical Theater",
    "Baseball Team",
    "Basketball Team",
    "ROTC",
    "Club Sports",
    "Orchestra",
    "Choral Groups",
    "Study Abroad",
    "Internship/Co-Op",
    "Newspaper",
    "Football Team",
    "Intramurals",
    "Radio Station",
    "TV Station",
    "Greek Life",
    "On-Campus Housing Available",
    "Lots of Green Space",
    "Eco-Friendly/Sustainable Campus",
    "Safety",
    "On-Campus Housing required- all four years",
    "Suite Style Housing",
    "Traditional Dorms",
    "Traditional Looking Buildings",
    "On-Campus Housing Required - Freshmen",
    "Modern Looking Buildings",
    "Free Mental Health Resources",
    "Openness",
    "Low Net Price",
    "Credit for Dual Enrollment (DE)",
    "Work Study/On Campus Job",
    "Credit for Advanced Placement (AP)",
    "Meet Full Financial Need",
    "Merit Scholarships",
    "HOPE/Zell Miller",
    "High 4 year grad rate",
    "Academic Common Market"
];